### ISSUE TITLE
Send empty NHSD-Session-URID value

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#125]
**Description** - Regarding testing of endpoint /AuditEvent - Send TES message. 
While testing negative test : Send empty NHSD-Session-URID value. We are keeping the value of header NHSD-Session-URID as empty and sending the request.

Error response received is - 
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Missing NHSD-Session-URID header"
            }
        }
    ]
}

Though header is passed in request but value is missing. Should we get error text as "Missing NHSD-Session-URID header value" ?

**Steps to reproduce** - These are attached below in file

**Expected Response code** - 400 Bad request
**Actual response code** - 400 Bad request

**Expected Response body** -
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "_Missing NHSD-Session-URID header value_"
            }
        }
    ]
}

**Actual response body** -
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "_Missing NHSD-Session-URID header_"
            }
        }
    ]
}

**Environment** - INT
**Severity** - Low

[Send empty NHSD-Session-URID value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6060201/Send.empty.NHSD-Session-URID.value.txt)

Attaching request in txt format as curl is not supported here.

@michael-kainos  Can you suggest your thoughts!

**Comment by michael-kainos** [comment]
@sonalVarma i don't think this is an issue. Closing
