### ISSUE TITLE
Getting 200 OK Response while Sending the invalid NHSD-Session-URID value and Null value in header 

### ISSUE THREAD

**Issue by vidyaguthala** [NHSDigital/summary-care-record-api#128]
Description - Regarding testing of endpoint /DocumentReference 
While testing negative test : Send invalid NHSD-Session-URID value and Send null NHSD-Session-URID value We are keeping the value of header NHSD-Session-URID as invalid and null  and sending the request.

Responses received is -
1.Send invalid NHSD-Session-URID value response:
[Send invalid NHSD-Session-URID value_Response body.txt](https://github.com/NHSDigital/summary-care-record-api/files/6068342/Send.invalid.NHSD-Session-URID.value_Response.body.txt)

2.Send null NHSD-Session-URID value response:
[Send null NHSD-Session-URID value_Response body.txt](https://github.com/NHSDigital/summary-care-record-api/files/6068350/Send.null.NHSD-Session-URID.value_Response.body.txt)

Steps to reproduce - These are attached below in file

Expected Response code - 400 Bad request
Actual response code - 200 Ok

Expected Response body -

    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Invalid NHSD-Session-URID header"
            }
        }
    ]
}

Environment - INT
Severity - Low
[Send invalid NHSD-Session-URID value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6068238/Send.invalid.NHSD-Session-URID.value.txt)

[Send null NHSD-Session-URID value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6068243/Send.null.NHSD-Session-URID.value.txt)

Attaching request in txt format as curl is not supported here.
@michael-kainos Could you please look into this issue

**Comment by michael-kainos** [comment]
Will investigate with NHS

**Comment by dawidskainos** [comment]
As agreed on a meeting with SCR clinicians (Monday 12.04) - setting correct User Role ID is the responsibility of consuming system. SCR API will not validate it. Therefore this issue can be closed.
