### ISSUE TITLE
Consent error is displayed for non-existing NHS number of patients

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#138]
Description -  Using nhs numbers provided by Michael in spreadsheet for MD , we are getting 201 "SCR uploaded successfully" message. If we are passing random NHS number (any 10-digit) eg. 1122334455, 9000000009
. We are getting error "There is no patient consent to view SCR"

Steps to reproduce -
Attached is the request in complete curl format -
[Upload SCR_random NHS number.txt](https://github.com/NHSDigital/summary-care-record-api/files/6139093/Upload.SCR_random.NHS.number.txt)

Screenshot -
![image](https://user-images.githubusercontent.com/75005842/111109119-218b0880-8580-11eb-9575-557ddcc80c51.png)

Expected Behavior -
Consent error should not be displayed for non-existing nhs number

Severity - Medium

Environment - NA

@michael-kainos  @dawidskainos

**Comment by michael-kainos** [comment]
@sonalVarma i understand the confusion here. This cannot be logged explicitly as this could inform a malicious party of NHS numbers that exist or not. Closing issue
