### ISSUE TITLE
When query Get SCR for patient 9693042298, an operation outcome is returned 

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#140]
**Describe the bug**
The adapter returned an operation outcome when call GET SCR for patient 9693042298 

**To Reproduce**
Make GET SCR call for patient 9693042298 

**Expected behavior**
It should return success response with scr payload

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: [e.g. chrome, safari]
 - Version: 10

**Additional context**
Operation outcome payload

{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "value",
      "details": {
        "text": "Unable to find ./addr in Spine response"
      }
    }
  ]
}

correlationId = 772D6D16-0A6B-4A9F-85CD-780523C6D20B
request-ID = 1C5A1806-9505-4991-89ED-EED1EA632A44

**Comment by michael-kainos** [comment]
Will investigate and fix in next release

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1208
