### ISSUE TITLE
Audi event call can be called with any kind of user /organisation credentials

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#141]
**Describe the bug**
At the moment, the audit can be called with any user/organisation/mhs credentials. It appears you can put the user/organisation/ASID that is not corresponding to the origin of the call or logged user.  

**To Reproduce**
 Call audit event call, with changing the UserSdsId, organisation Ods, Asid to an arbitrary number or value, the call still pass. 

**Expected behavior**
There should be some validation against the logged users (Organisation and SD user ID) and the origin of the call (for ASID).

**Comment by michael-kainos** [comment]
This request is purley proxied to spine so there is no validation for the SCR API here. We will investigated a resolution here. It is possible this is a spine issue.

**Comment by dawidskainos** [comment]
The Care Record Guarantee stipulates that local systems are responsible for ensuring users are accessing national services within the correct context, with applicable access controls in place
