### ISSUE TITLE
While sending invalid NHSD-Session-URID value for uploading SCR is giving 201 -Created response status

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#145]
**Description** -
When sending a request with passing invalid NHSD-Session-URID value (for eg. 12345) for endpoint /Bundle :POST for uploading SCR is giving successful response 201 Created with blank response body

**Steps to reproduce** -
Attached is the request in curl format.
[Send invalid NHSD-Session-URID value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6146753/Send.invalid.NHSD-Session-URID.value.txt)

**Expected Behavior** - 
Error message should be displayed
**Actual behavior** -  201 Created is getting displayed

**Screenshot** -
![image](https://user-images.githubusercontent.com/75005842/111269691-f0303c80-8654-11eb-83e7-dd4229e7000c.png)

*Desktop (please complete the following information):**
 - OS: [Windows]
 - Tool - Postman

@michael-kainos Please look to the issue. Thanks!

**Comment by michael-kainos** [comment]
Will investigate with NHS

**Comment by dawidskainos** [comment]
As agreed on a meeting with SCR clinicians (Monday 12.04) - setting correct User Role ID is the responsibility of consuming system. SCR API will not validate it. Therefore this issue can be closed.
