### ISSUE TITLE
Sending null NHSD-Session-URID value to the header is giving 201 Created response code

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#146]
**Describe the bug**
When sending a POST:/Bundle request for uploading an SCR, with NHSD-Session-URID as null is giving us successful response i.e. 201 created with blank request body

**To Reproduce**
Attached is the request in curl format -
[Send null NHSD-Session-URID value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6146810/Send.null.NHSD-Session-URID.value.txt)

**Expected behavior**
Error message should be displayed

**Actual behavior**
201 Created is received in response status with blank response body

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111271067-b3fddb80-8656-11eb-92ae-a1458dabfb0a.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. Windows
 - Tool -  Postman
 - Version: [e.g. 22]

@michael-kainos Please suggest!

**Comment by dawidskainos** [comment]
As agreed on a meeting with SCR clinicians (Monday 12.04) - setting correct User Role ID is the responsibility of consuming system. SCR API will not validate it. Therefore this issue can be closed.
