### ISSUE TITLE
Send request for uploading an SCR with passing type as null

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#148]
**Describe the bug**
As validation are applied to data types , and we are sending request for uploading an SCR passing required field type in payload as null is giving successful response 201 - Created with blank response body

**To Reproduce**
Attached is the request in curl format -
[Send request with type as null  in payload.txt](https://github.com/NHSDigital/summary-care-record-api/files/6146938/Send.request.with.type.as.null.in.payload.txt)

**Expected behavior**
Error should be displayed as it is the mandatory field in payload and cannot be passed as null as it is defined string in document

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111273444-d80eec00-8659-11eb-82d8-505136075f74.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [Windows]
 - OS: [e.g.10
 - Tool - Postman
 - Version: [e.g. 22]

@michael-kainos Please suggest!

**Comment by michael-kainos** [comment]
Will implement validation here and release in next version

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1254

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Unsupported Bundle.type: null"
            }
        }
    ]
}
