### ISSUE TITLE
Send invalid or null NHSD-Session-URID value for get latest SCR identifier is giving 200 response

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#149]
**Describe the bug**
When passing an invalid value for NHSD-Session-URID or null is giving successful response 200 OK

**To Reproduce**
Attached is the request in curl format
[Get null NHSD-Session-URID value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6146986/Get.null.NHSD-Session-URID.value.txt)
[Get invalid NHSD-Session-URID value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6146987/Get.invalid.NHSD-Session-URID.value.txt)

**Expected behavior**
Error should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111274419-f9bca300-865a-11eb-8a8b-ee4214a6183b.png)
![image](https://user-images.githubusercontent.com/75005842/111274467-07722880-865b-11eb-915f-8e8ecb25ce0d.png)

**Desktop (please complete the following information):**
 - OS: [Windows
 - Tool - Postman
 - Version: [e.g. 22]

@michael-kainos Please suggest!

**Comment by michael-kainos** [comment]
Will investigate with NHS

**Comment by dawidskainos** [comment]
As agreed on a meeting with SCR clinicians (Monday 12.04) - setting correct User Role ID is the responsibility of consuming system. SCR API will not validate it. Therefore this issue can be closed.
