### ISSUE TITLE
Query - Send invalid or null NHSD-Session-URID value for endpoint /AuditEvent 

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#150]
**Describe the bug**
While sending request for invalid NHSD-Session-URID or null NHSD-Session-URID value, is giving error 400 - bad request with error message - Unauthorized
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Access Denied - Unauthorised"
            }
        }
    ]
}

**To Reproduce**
Attached is the request in curl format
[Send invalid NHSD-Session-URID value_audit event.txt](https://github.com/NHSDigital/summary-care-record-api/files/6147030/Send.invalid.NHSD-Session-URID.value_audit.event.txt)
[Send null NHSD-Session-URID value_audit event.txt](https://github.com/NHSDigital/summary-care-record-api/files/6147031/Send.null.NHSD-Session-URID.value_audit.event.txt)

**Expected behavior**
Unauthorized error should not be displayed as it is giving 400 Bad request or if it is the access denied issue  - 401 should be the response

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111275582-4f457f80-865c-11eb-97c2-7754164c8d10.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Tool - Postman
 - Version: [e.g. 22]

@michael-kainos Please suggest!

**Comment by michael-kainos** [comment]
Will investigate with NHS

**Comment by dawidskainos** [comment]
As agreed on a meeting with SCR clinicians (Monday 12.04) - setting correct User Role ID is the responsibility of consuming system. SCR API will not validate it. Therefore this issue can be closed.
