### ISSUE TITLE
Practitioner Role example does not comply with the specification and still pass the upload Scr call

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#152]
**Describe the bug**
The PractitionerRole seems to be expected to have a sdsRoleProfileId identifier, but the UploadScr example contains PractitionerRole without an identifier and still passes.

**To Reproduce**
call upload SCR with upload example in GitHub, and the call still passes.

**Expected behavior**
Fails, as it does not comply with the specification

**Comment by michael-kainos** [comment]
Will update the specification to clarify the conditions here

**Comment by michael-kainos** [comment]
This will be fixed by https://github.com/NHSDigital/summary-care-record-api/issues/152

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1257

**Comment by dawidskainos** [comment]
Spec published.
