### ISSUE TITLE
Upload SCR with title in the section, but when get SCR for the same patient, the title is not returned. 

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#153]
**Describe the bug**
When upload SCR with section with title, but when get SCR for the same patient again.. the title is not returned. This seems inconsistent between get SCR and upload SCR. 

**To Reproduce**
1. Make Upload SCR call, with section containing title, make sure it upload succesfully
2.  Make Get SCR call for the same patient, the title in the section does not appear. 

**Expected behavior**
The title in the section appear, so the rendering is consistent. 

**Screenshots**

The upload SCR payload
![image](https://user-images.githubusercontent.com/2870531/111513534-d1ab6d80-8748-11eb-95d3-e41f2027af05.png)

The get SCR payload for the same patient after upload SCR successful.
![image](https://user-images.githubusercontent.com/2870531/111513807-1505dc00-8749-11eb-9070-bc987c47796a.png)

**Comment by michael-kainos** [comment]
Will investigate and fix in next version

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1264

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by jhoey-med** [comment]
### Retest

- Sign In > Click GP System
- Find NHS Number: 9693041747
- Patient consent is: Patient consents to view SCR (Current)
- Select Data Input from dropdown 'Minimal'.
- Confirm only sub sections Allergies and Adverse Reactions/Acute Medications/Current Repeat Medications/Discontinued Repeat Medications are displayed
- Click 'Upload SCR'
- SCR uploaded successfully with message in UI: "SCR successfully uploaded with new Document identifier '20b010dd-fb51-4670-a597-a1a678c6f57a'"
- API Call Log:
- GET Document reference request and response (GET /DocumentReference). HTTP Status Code of 200 received
- POST /Bundle. Upload patient's Summary Care Record (Upload SCR Request and response). HTTP Status Code of 201 received
- Navigate to 'Hospice System'
- Find NHS Number: 9693041747
- Click 'View SCR'
- Confirmed SCR data rendered matches that created in Upload

Please see screenshots and payloads attached

[48687_Retest1_9693041747_GET SCR Request.txt](https://github.com/NHSDigital/summary-care-record-api/files/6334961/48687_Retest1_9693041747_GET.SCR.Request.txt)
[48687_Retest1_9693041747_GET SCR Response.txt](https://github.com/NHSDigital/summary-care-record-api/files/6334963/48687_Retest1_9693041747_GET.SCR.Response.txt)
[48687_Retest1_9693041747_Upload SCR_POST Bundle Request.txt](https://github.com/NHSDigital/summary-care-record-api/files/6334964/48687_Retest1_9693041747_Upload.SCR_POST.Bundle.Request.txt)
[48687_Retest1_9693041747_Upload SCR_POST Bundle Response.txt](https://github.com/NHSDigital/summary-care-record-api/files/6334965/48687_Retest1_9693041747_Upload.SCR_POST.Bundle.Response.txt)

<img width="959" alt="48687_Retest1_9693041747_GET SCR" src="https://user-images.githubusercontent.com/81386191/115217450-711f9f80-a0fd-11eb-9503-8bcb2c90757a.png">

GitHub Issue 153 Closed
