### ISSUE TITLE
Upload SCR: Structural issue - Missing parameter id in resource type: composition is giving 201 created response

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#156]
**Describe the bug**
The id is required parameter in payload for resource type: composition whose example value can be : 25FCE159-C82D-482B-8EA9-86DEF2C3929B. If we are not passing it in payload, still we are receiving 201 Created response

**To Reproduce**
Below is the complete request attached -
[Missing id parameter in resource type composition.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163265/Missing.id.parameter.in.resource.type.composition.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111612430-75f1ea80-8803-11eb-90fe-07e8cb3a2244.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos @dawidskainos  Can you please check and let us know

**Comment by michael-kainos** [comment]
will update specification

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1253

**Comment by dawidskainos** [comment]
Spec published.

**Comment by sonalVarma** [comment]
Spec is updated making it optional field
