### ISSUE TITLE
Upload SCR: Structural issue - Missing identifier in payload

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#157]
**Describe the bug**
The identifier is required parameter in payload which consists of system and value. If we are not passing it in payload, still we are receiving 201 Created response

**To Reproduce**
Below is the complete request attached -
[Missing identifier parameter.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163304/Missing.identifier.parameter.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111613289-5ad3aa80-8804-11eb-973c-706ecbc8a931.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos @dawidskainos

**Comment by michael-kainos** [comment]
Will fix this in next release version

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1252

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Missing Composition.identifier for system: https://tools.ietf.org/html/rfc4122"
            }
        }
    ]
}
