### ISSUE TITLE
Upload SCR: Structural issue - Missing status

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#158]
**Describe the bug**
The status is required parameter in payload whose default value is final. If we are not passing it in payload, still we are receiving 201 Created response

**To Reproduce**
Below is the complete request attached -
[Missing status.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163327/Missing.status.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111613718-ce75b780-8804-11eb-8b4f-668b9927921b.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos @dawidskainos

**Comment by michael-kainos** [comment]
Will fix this in the next release version

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1251

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Invalid composition.status: null"
            }
        }
    ]
}
