### ISSUE TITLE
Upload SCR: Structural issue - Missing category field in payload

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#160]
**Describe the bug**
Category is required field which consists of -
 "category": [
          {
            "coding": [
              {
                "system": "http://snomed.info/sct",
                "code": "163171000000105",
                "display": "Care Professional Documentation"
              }
            ]
          }
        ],  If we are not passing it in payload, still we are receiving 201 Created response

**To Reproduce**
Below is the complete request attached -
[Missing category.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163402/Missing.category.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111614844-1517e180-8806-11eb-9ad4-0b68d949dc69.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]
 - 
@michael-kainos @dawidskainos

**Comment by michael-kainos** [comment]
Will fix in next release version

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1248

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Composition.category element is missing"
            }
        }
    ]
}
