### ISSUE TITLE
Upload SCR: Structural issue - Missing parameter relatesTo

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#162]
**Describe the bug**
In relatesTo, the targetIdentifier and its value are required parameter in payload- 
"relatesTo": [
          {
            "code": "replaces",
            "targetIdentifier": {
              "value": "D18B57ED-992E-45A2-A6AF-55200D20F48E"
            }
          }
        ],

If we are not passing it in payload, still we are receiving 201 Created response

**To Reproduce**
Attached is complete request -
[Missing parameter relatesTo in payload.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163464/Missing.parameter.relatesTo.in.payload.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111616154-915ef480-8807-11eb-9ade-e532b5a4acc3.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by michael-kainos** [comment]
Will update specification to mention that relatesTo is optional however the sub elements are required, as this would be the case if relatesTo is provided. Will add a fix for validation of these if they are provided. Next release version.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1243

**Comment by sonalVarma** [comment]
Spec is updated making it optional field.
