### ISSUE TITLE
Upload SCR: Structural issue - Missing object sds-user-id and value under resource type Practitioner 

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#163]
**Describe the bug**
Identifier objects system and value are required fields for resource type Practitioner -
"identifier": [
          {
            "system": "https://fhir.nhs.uk/Id/sds-user-id",
            "value": "676789689789"
          }
        ],  If we are not passing it in payload, still we are receiving 201 Created response

**To Reproduce**
Attached request below - 
[Missing object for identifier for resource type practitioner.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163538/Missing.object.for.identifier.for.resource.type.practitioner.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111617284-eb13ee80-8808-11eb-9482-2d6bf56a833f.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by michael-kainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1242

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Invalid practitioner identifier system: null"
            }
        }
    ]
}
