### ISSUE TITLE
Upload SCR: Structural issue - Missing value object for sds-role-profile-id for resource type PractitionerRole

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#164]
**Describe the bug**
Resource type practitionerRole consists of object system and value, if we are not passing system or value to it, still it is giving 201 created response
"resource": {
        "resourceType": "PractitionerRole",
        "id": "C89A53D3-E063-4023-B89C-1A105ABAABB7",
        "identifier": [
          {
            "**system**": "http://fhir.nhs.net/Id/sds-role-profile-id",
            "**value**": "673836492727"
          }

**To Reproduce**
Attached is complete request - 
[Missing object value for resource type practitionerRole.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163581/Missing.object.value.for.resource.type.practitionerRole.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111617920-c3715600-8809-11eb-9163-dba864651c4d.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by michael-kainos** [comment]
Will be fixed by https://github.com/NHSDigital/summary-care-record-api/issues/152
