### ISSUE TITLE
Upload SCR: Structural issue - Missing object system and display for resource type Encounter

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#165]
**Describe the bug**
For resource type Encounter, coding consists of object-  system, code and display which are required fields, if we are not passing system and display to the payload, still we are getting 201 created response 
"coding": [
                  {
                    "**system**": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
                    "code": "AUT",
                    "**display**": "author"
                  }
                ]

**To Reproduce**
Attached is request -
[Missing parameter system and display for resource parameter encounter.txt](https://github.com/NHSDigital/summary-care-record-api/files/6168694/Missing.parameter.system.and.display.for.resource.parameter.encounter.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111618710-b99c2280-880a-11eb-8faa-b0f98e129de7.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1241

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Unsupported encounter participant system: null"
            }
        }
    ]
}
