### ISSUE TITLE
Upload SCR: Structural issue: Missing period object in payload

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#166]
**Describe the bug**
Period object is required field to be passed in payload with string start time. If it is not passed, still we are getting 201 created response
"period": {
              "start": "2020-11-17T01:00:00+00:00"
            },

**To Reproduce**
Attached is request -
[Missing period object.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163644/Missing.period.object.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111619213-4e068500-880b-11eb-87a0-4296e842d8e1.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@dawidskainos  @michael-kainos

**Comment by dawidskainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1240

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Encounter.participant.period.start element is missing"
            }
        }
    ]
}
