### ISSUE TITLE
Upload SCR: Structural issue: Missing id for resource type organization

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#167]
**Describe the bug**
id is required parameter for resource type organization. If we are not passing it in payload, still we are getting 201 response
"resource": {
        "resourceType": "Organization",
        "**id**": "CD7FAF21-0126-456E-B681-703571153CA3",

**To Reproduce**
Attached is request -
[Missing id for resource type organization.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163673/Missing.id.for.resource.type.organization.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111619865-10eec280-880c-11eb-9644-e573a3077a00.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
We will amend the spec as this should be optional. Will republish.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1238

**Comment by dawidskainos** [comment]
Spec published.

**Comment by sonalVarma** [comment]
Spec is updated. ID is now optional field.
