### ISSUE TITLE
Upload SCR: Structural issue - Missing value ods-organization-code for resource type organization is giving 201 created response

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#168]
**Describe the bug**
ods-organization-code and its value is required for resource type organization. If we are not passing it in payload still it is giving 201 created

 "resource": {
        "resourceType": "Organization",
        "id": "92CB3A00-A4E2-485F-8671-6E2E499536DB",
        "identifier": [
          {
            "system": "https://fhir.nhs.uk/Id/ods-organization-code",
            **"value": "57435939053"**
          }

**To Reproduce**
Attached request -
[Missing org code for resource type organization.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163702/Missing.org.code.for.resource.type.organization.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111620597-f36e2880-880c-11eb-8703-bbf7dbec6139.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will update the specification to clarify the conditions here.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1234

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Failed to parse JSON encoded FHIR content: com.google.gson.stream.MalformedJsonException: Expected name at line 891 column 12 path $.entry[22].resource.identifier[0].system"
            }
        }
    ]
}
