### ISSUE TITLE
Upload SCR: Structural issue - Missing parameter id from resource type relatedPerson

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#169]
**Describe the bug**
Id is required field for relatedPerson resource type. If we are not passing it in payload, then too, we are getting 201 created response
 "resource": {
        "resourceType": "RelatedPerson",
        **"id": "B0A64A15-3552-4525-8305-1DBFDF548C97",**
        "patient": {
          "reference": "Patient/565B3BEF-9A19-4763-8887-9F7CB75995E3"
        },

**To Reproduce**
Attached request -
[Missing id from resourcetype relatedPerson.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163807/Missing.id.from.resourcetype.relatedPerson.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111622637-71333380-880f-11eb-800d-30c700608c9f.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
We will amend the spec as this should be optional. Will republish.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1233
