### ISSUE TITLE
Upload SCR: Structural issue - Missing relationship objects from resource type relatedPerson

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#170]
**Describe the bug**
The relationship structure contains system, display and code as required field. if we are not passing it in payload, still we are getting 201 created response
 "relationship": [
          {
            "coding": [
              {
                **"system": "https://fhir.nhs.uk/STU3/ValueSet/PersonRelationshipType-1",
                "code": "01",
                "display": "Brother"**
              }
            ]
          }
        ],

**To Reproduce**
Attached request -
[Missing system display and code in relationship for relatedPerson.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163839/Missing.system.display.and.code.in.relationship.for.relatedPerson.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111623260-24039180-8810-11eb-9b21-8b5d360f4e47.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1232

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
Response code - 400 Bad request
Response body - 
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Unsupported RelatedPerson.relationship.coding.system: null"
            }
        }
    ]
}
