### ISSUE TITLE
Upload SCR: Structural issue - Missing array name for resource type relatedPerson

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#171]
**Describe the bug**
name array is required in payload. if we are not passing, then too we are getting 201 created response
],
        "**name**": [
          {
            "text": "JONES Bob"
          }
        ]
      }

**To Reproduce**
Attached request -
[Missing name array.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163861/Missing.name.array.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111623717-befc6b80-8810-11eb-94cf-51128d4106bc.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1231

**Comment by sonalVarma** [comment]
Retested this defect.
Response code - 400 Bad request
Response body - {
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Missing RelatedPerson.name element"
            }
        }
    ]
}
