### ISSUE TITLE
Upload SCR: Structural issue - Missing identifier for resource type observation

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#172]
**Describe the bug**
Identifier and value are required fields in payload for resource type observation. If we are not passing it in payload still it is giving 201 created response

**To Reproduce**
Attached request -
[Missing identifier from resource type observation.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163904/Missing.identifier.from.resource.type.observation.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111624259-75f8e700-8811-11eb-9575-a8208f478fb1.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1230

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
Response code - 400 Bad request

Response body - 
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Observation.identifier.value is missing"
            }
        }
    ]
}
