### ISSUE TITLE
Upload SCR: Structural issue - Missing system, code and display string from coding object is giving 201 created response

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#173]
**Describe the bug**
System , code and display are required fields for coding object for resource type observation. If we are not passing them to payload, still we are getting 201 created response
"category": [
          {
            "coding": [
              {
                **"system": "http://snomed.info/sct",
                "code": "163141000000104",
                "display": "Investigation Results"**
              }
            ]
          }

**To Reproduce**
Attached request - 
[Missing system code display for resource type observation.txt](https://github.com/NHSDigital/summary-care-record-api/files/6168662/Missing.system.code.display.for.resource.type.observation.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111624877-3bdc1500-8812-11eb-816a-47be35b3d75e.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1229

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
Response code - 400 Bad request
Response body -
