### ISSUE TITLE
Upload SCR: Structural issue - Missing id from resource type device

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#174]
**Describe the bug**
id is required field for resource type device. If we are not passing it in payload, still it is giving 201 created response
 "resource": {
        "resourceType": "Device",
        **"id": "4FCE15F1-6969-41BD-9298-BE595CB6E995",**
        "identifier": [
          {

**To Reproduce**
Complete request -
[Missing id from resource type device.txt](https://github.com/NHSDigital/summary-care-record-api/files/6163977/Missing.id.from.resource.type.device.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111625408-d3d9fe80-8812-11eb-9daf-80112f01b2d7.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
We will amend the spec as this should be optional. Will republish.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1228

**Comment by dawidskainos** [comment]
Spec published.

**Comment by sonalVarma** [comment]
id is now optional field in spec.
