### ISSUE TITLE
Upload SCR: Structural issue - Missing device name and type is giving 201 created response

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#176]
**Describe the bug**
device name and type string are required fields in payload, if we are not passing them, then too we are receiving 201 Created response

**To Reproduce**
Complete request -
[Missing device name and type.txt](https://github.com/NHSDigital/summary-care-record-api/files/6164024/Missing.device.name.and.type.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111626292-d1c46f80-8813-11eb-8b61-070ecdf3db36.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will update the specification to clarify the conditions here

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1226

**Comment by dawidskainos** [comment]
Spec published.

**Comment by sonalVarma** [comment]
Verified the spec .
