### ISSUE TITLE
Upload SCR: Structural issue - Missing code and display from resource type device

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#177]
**Describe the bug**
Code and display are required string for array coding . If we are not passing it to the payload, then too we are getting 201 created response

**To Reproduce**
Complete request -
[Missing code and display from coding array.txt](https://github.com/NHSDigital/summary-care-record-api/files/6164064/Missing.code.and.display.from.coding.array.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111626935-8b234500-8814-11eb-8bc0-93a382fcdc1a.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will update the specification to clarify the conditions here

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1224

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
Restested this issue. Now getting 400- Bad request with response body - {
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Missing mandatory elements: Device.type"
            }
        }
    ]
}
