### ISSUE TITLE
Upload SCR: Structural issue - Missing version value in resource type device

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#178]
**Describe the bug**
value of version is required field in payload, if we are not passing it , it is giving 201 created response
},
        "version": [
          {
            **"value": "v.1.10.245-beta"**
          }
        ],
     

**To Reproduce**
Complete request -
[Missing version value.txt](https://github.com/NHSDigital/summary-care-record-api/files/6164094/Missing.version.value.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111627336-f3722680-8814-11eb-96f6-fa3c90085742.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will update the specification to clarify the conditions here

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1223

**Comment by dawidskainos** [comment]
Spec published.

**Comment by sonalVarma** [comment]
Verified the version is now updated to optional field in spec.
