### ISSUE TITLE
Upload SCR: Structural issue - Missing note text is giving 201 created response

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#179]
**Describe the bug**
Note text is required field in payload, if we are not passing it, then too it is giving 201 created response

**To Reproduce**
Complete request -
[Missing note .txt](https://github.com/NHSDigital/summary-care-record-api/files/6164111/Missing.note.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111627662-4e0b8280-8815-11eb-9650-d5a37d3b863c.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
We will amend the spec as this should be optional. Will republish.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1222

**Comment by dawidskainos** [comment]
Spec published.
