### ISSUE TITLE
Update consent: Structural issue - Missing NHS number value is giving 500 internal server error

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#180]
**Describe the bug**
The nhs number value is required in payload. If we are not passing it , then it is giving 500 internal server error
 "part":  [
        {
          "name": "nhsNumber",
          **"valueString": "9693044479"**
        },
        {
          "name": "permissionCode",
          

**To Reproduce**
Attached request - 
[Missing nhs number value field.txt](https://github.com/NHSDigital/summary-care-record-api/files/6164165/Missing.nhs.number.value.field.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111628465-400a3180-8816-11eb-8efc-cd0194d5df60.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
Will add a fix in next release version

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1209

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
@dawidskainos  , The issue is fixed now. The response code received is 400 - Bad request with response body -
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "**Parameter.Part named 'nhsNumber' with not empty value not found**"
            }
        }
    ]
}


Can you please once check the error text message . _with not empty value not found_

**Comment by dawidskainos** [comment]
@sonalVarma I changed the error message. I hope it makes more sense now.
Ready for retest.

**Comment by sonalVarma** [comment]
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Missing value for Parameter.Part 'nhsNumber'"
            }
        }
    ]
}
