### ISSUE TITLE
Send TMS: Structural issue - Missing text for role in payload

### ISSUE THREAD

**Issue by sonalVarma** [NHSDigital/summary-care-record-api#181]
**Describe the bug**
Text is required field for role in payload, if we are not passing it, then too we are receiving 201 created response
    "value" : "YGMYH"
      }
    },
    "role" : [ {
      **"text" : "General Practitioner"**
    } ],
   

**To Reproduce**
Complete request -
[Missing text for role.txt](https://github.com/NHSDigital/summary-care-record-api/files/6164222/Missing.text.for.role.txt)

**Expected behavior**
This can be treated as structural/syntax issue and should give invalid response possibly, 400 - Bad request.

**Screenshots**
![image](https://user-images.githubusercontent.com/75005842/111629463-549af980-8817-11eb-8ab1-1e05d7cedf80.png)

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

@michael-kainos  @dawidskainos

**Comment by dawidskainos** [comment]
We will amend the spec as this should be optional. Will republish.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1211

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.

**Comment by sonalVarma** [comment]
Retested this defect. Now getting expected response 400 - Bad request with response body -
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "details": {
                "text": "Expecting at least one non empty 'role' for 'agent' entry with system https://fhir.nhs.uk/Id/sds-user-id"
            }
        }
    ]
}

Closing this issue.
