### ISSUE TITLE
Some patient fail to get SCR  even after get patient consent

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#191]
**Describe the bug**
One particular patient 9693041488, fail to to return any document reference (result: empty Bundle), even after patient consent call (with YES)

**To Reproduce**
1. call update patient consent with YES for patient 9693041488,
2. call document reference : return empty bundle

**Expected behavior**
We expect a result, as the patient is given to us for SCR test unless it is specified as a case for a patient with no SCR upload available. 

**Additional info**
we make the call to INT with this information:
CorrelationId = B61D5AF5-0363-43C9-8911-D93DAD5BC163
requst-Id = 923E667F-C7A1-4FF4-AE37-B41B7A60FAB9

**Comment by dawidskainos** [comment]
@Kusnaditjung Spine returns the following error for this patient: "[PSIS-30312] - Case Instance not found. 9693041488". It looks like data issue not related to SCR API.

**Comment by Kusnaditjung** [comment]
Is this patient  need to be excluded from SCR API adapter testing ??

**Comment by michael-kainos** [comment]
Analysing data in spine with NHS

**Comment by michael-kainos** [comment]
Closed as this request was using patient data with no existing SCR record
