### ISSUE TITLE
Inconsistent reference used in sample data (and thus processing of the reference data)

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#192]
**Describe the bug**
The reference value used in the sample data is inconsistent, some of them using pattern
"[ResourceType]/[Guid]" => e.g Patient/565B3BEF-9A19-4763-8887-9F7CB75995E3
and other such as Condition entry reference in Diagnoses section
"Guid" => e.g "6ECDAE6D-32AB-421C-AA8F-0B1ABA454C70"

**To Reproduce**
- check sample data

**Expected behavior**
Consistent use of formatting across all reference value in one sample ?? 

**Additional**
Though the reference value format may be inherited from the underlying provider (EMIS or TPP)... I think the adapter should normalize this and provide a consistent reference value format and thus make it easy for the market entrant to reference other FHIR resource in the bundle.

**Comment by dawidskainos** [comment]
Will be fixed in next release.

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1264

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.
