### ISSUE TITLE
For the GET SCR, some reference value in the bundle does not have corresponding FHIR resource

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#193]
[SCRREsponse_9693041291.txt](https://github.com/NHSDigital/summary-care-record-api/files/6184471/SCRREsponse_9693041291.txt)
**Describe the bug**
For the GET SCR result, some reference values in the bundle do not have a corresponding FHIR resource. And because the reference just a GUID, we don't know what resource this is being referred to as well. 

If this has been out of scope, should it be excluded in the FHIR as entries ??

**To Reproduce**
1. Make GET SCR call to patient 9693041291
2. the response is attached
[SCRREsponse_9693041291.txt](https://github.com/NHSDigital/summary-care-record-api/files/6184473/SCRREsponse_9693041291.txt)

3. Check for example LifeStyle text section entry reference for example
    45BED57E-CE9E-48F3-A29E-3FEC47EBBF5E

**Expected behavior**
Either:
- Include the referenced FHIR resource
- Exclude the text section entry references if the entries are out of scope.

**Additional context**
If this still needs to be included, then what will be the benefit?? and what kind of processing we can do ?? and will be there any missing information/gap to do so??

[SCRREsponse_9693041291.txt](https://github.com/NHSDigital/summary-care-record-api/files/6184474/SCRREsponse_9693041291.txt)

**Comment by dawidskainos** [comment]
Will be fixed in next release

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1264

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.
