### ISSUE TITLE
GET SCR response contain many invalid "\n" string in the Composition text section Div element which should comply with HTML 4

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#194]
**Describe the bug**
The response that coming back from GET SCR contain many "\n" string which is not valid according to  Div element constraint (XHTML). 

**To Reproduce**
1. make any GET SCR call to any patient
2. check the response in the composition text section. it contains many "\n" string

**Expected behavior**
Should be clean XHTML format

**Comment by dawidskainos** [comment]
Will be fixed in next release.

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1263

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.
