### ISSUE TITLE
Sending upload SCR with covid entry and with encounter, return operation outcome

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#203]
**Describe the bug**
The issue only appears if the encounter has participant, 

**To Reproduce**
1. Send upload SCR with the encounter (see attachment)
2. Result : operation outcome with Text : Bundle has no Device resource referencing org.hl7.fhir.r4.model.Organization@7df8d0f8

    Correlation-ID: 2346c78e-5f9a-4021-ac9e-f77b50263468

**Expected behavior**
Should pass

**Additional context**
[DeviceError.txt](https://github.com/NHSDigital/summary-care-record-api/files/6199911/DeviceError.txt)

**Comment by dawidskainos** [comment]
Will be fixed in next release

**Comment by dawidskainos** [comment]
will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1256

**Comment by dawidskainos** [comment]
Deployed to INT and ready for re-test.
