### ISSUE TITLE
Encounter fails when participant type is valid

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#204]
**Describe the bug**
Upload SCR with encounter with participant type = WIT or CON or may other choices (which is valid according to this terminology
http://terminology.hl7.org/CodeSystem/v3-ParticipationType, which can be accessed here
 https://terminology.hl7.org/2.1.0/CodeSystem-v3-ParticipationType.html

return an operation outcome

**To Reproduce**
1.  Send Upload SCR with encounter participant type other than AUT, e.g CON, WIT, PPRF, etc
2. Return operation outcome with text : 
"Invalid encounter https://int.api.service.nhs.uk/summary-care-record/FHIR/R4/Encounter/0F670DDF-3856-4201-964E-730FC3929FCB participant code WIT"

Correlation ID = ff8c77dc-07b6-42c5-9207-e492dbfe7260

**Expected behavior**
should be able to process, if the vocab is valid according to the terminology.

**Comment by dawidskainos** [comment]
SCR supports only subset of the linked terminology. Will update the spec to reflect that.

**Comment by dawidskainos** [comment]
Will be fixed in https://gpitbjss.atlassian.net/browse/NIAD-1241
