### ISSUE TITLE
Upload SCR with covid Diagnoses and Result codes, but when query the SCR for same patient, only the Diagnoses that is returned.

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#205]
**Describe the bug**
Upload SCR successfully with Covid Diagnoses and Result codes, 
but when query the SCR only the Diagnoses code is returned and also it is not referenced in the Diagnoses text section entries. 

**To Reproduce**
1. Upload SCR with covid diagnoses, and result codes
2. Get SCR for the same patient,
3. The Investigation Results is not returned, and also the diagnoses code is not referenced in the Diagnoses text section entries.

**Expected behavior**
The covid diagnoses and investigation result codes should be both returned on SCR call. 

Upload SCR payload:
[MissingResult_Upload.txt](https://github.com/NHSDigital/summary-care-record-api/files/6200076/MissingResult_Upload.txt)

Get SCR payload:

[MissingResult_GetSCR.txt](https://github.com/NHSDigital/summary-care-record-api/files/6200078/MissingResult_GetSCR.txt)

**Comment by dawidskainos** [comment]
@Kusnaditjung you are uploading an Observation resource with snomed code 1300721000000109 - COVID-19 confirmed by laboratory test. That should be a Condition resource.

**Comment by Kusnaditjung** [comment]
@dawidr-kainos, I have fixed it, and it now returns both, however, the entry (linkage) in the Text section still missing.

**Comment by dawidskainos** [comment]
@Kusnaditjung could you please upload request and response body?
