### ISSUE TITLE
General Inquiry

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#206]
**Describe the bug**
When doing the integration work, I encountered a number of issues, which I think I will raise here. 
In general, I wonder if SCR has official profiles we need to follow apart from the YAML specification in this repo ??

I found the profiles in this link https://simplifier.net/guide/SummaryCareRecordWithCodedData/AllAssets#AllCodeSystems

but apparently, I found there is a constraint that does not comply with this profile, for example the Device resource seems not allowed to be used in the composition. author, but the profile permits it.  There may be others, but this just an example. 

If the profiles are not followed strictly, then there should be some guidance somewhere, or updating the YAML specification to reflect that (at the moment, the yaml spec also does not limit it to practitioner role only)

**Comment by dawidskainos** [comment]
@Kusnaditjung There are no profiles dedicated for SCR. SCR spec is based on UK Core profiles.
