### ISSUE TITLE
Changes or loss of information fhir resource in GET SCR upon upload SCR (not affecting UI rendering)

### ISSUE THREAD

**Issue by Kusnaditjung** [NHSDigital/summary-care-record-api#208]
**Describe the bug**

When GET SCR after uploading SCR, some information in a number FHIR resources is lost.
Note, this issue only logs changes that are not affecting UI rendering. (Changes that affecting UI rendering has been logged separately in other issues)

**To Reproduce**
1. Upload SCR for patient 9693042204, with the attached message
2. GET SCR for the same patient, see the attached message 
3. See 
* Organisation resource, the address is not fully preserved
* Practitioner resource, the name is not fully preserved
* PractitionerRole resource, the organization is missing, and job role is missing
* Condition resource, the encounter, and clinical status is missing, and there is additional  verificationStatus

**Expected behavior**
Information is preserved, some are important particularly for information linking (resource references) though not required for UI rendering. 

**Upload SCR attachment**
[NotAffectingRendering_UploadSCR.txt](https://github.com/NHSDigital/summary-care-record-api/files/6203701/NotAffectingRendering_UploadSCR.txt)

**GET SCR attachment**
[NotAffectingRendering_GETSCR.txt](https://github.com/NHSDigital/summary-care-record-api/files/6203703/NotAffectingRendering_GETSCR.txt)

**Comment by dawidskainos** [comment]
"Practitioner resource, the name is not fully preserved" - when name.text is provided then name.given, name.family are ignored. Since Spine supports only single field name value we will also support text only (otherwise round-trip mapping would not be possible anyway)

**Comment by dawidskainos** [comment]
"the organization is missing" - when author is SDS user (has "http://fhir.nhs.net/Id/sds-role-profile-id" identifier) then there's no need to pass organization along. In Spine it's represented as UKCT_MT160018UK01.AgentPersonSDS which does not have a reference to an organization.

**Comment by dawidskainos** [comment]
"and job role is missing" - when author is SDS user (has "http://fhir.nhs.net/Id/sds-role-profile-id" identifier) then job role coding is not preserved as there's no place to store it within UKCT_MT160018UK01.AgentPersonSDS. See https://simplifier.net/guide/SummaryCareRecordWithCodedData/CodedEntriesforCOVID-19Mappings#ParticipantCodedEntry

**Comment by dawidskainos** [comment]
"Organisation resource, the address is not fully preserved" - made a change to support text field only (spec updated too)

**Comment by dawidskainos** [comment]
Deployed to INT and ready for retest.
