### ISSUE TITLE
SCR - HTTP Status Code 400 Bad request received when consent updated to Emergency access

### ISSUE THREAD

**Issue by jhoey-med** [NHSDigital/summary-care-record-api#211]
### SUMMARY

A 400 Bad request is received when patient with NHS Number _9693041488_ updates consent from 'No consent to view SCR' to 'Emergency access to view SCR'. Error description received in UI: 
>" SCR API error on Send Alert: Operation outcome (400). Code : Value. Detail text: Resource not found (Correlation ID = ef55ad09-6d6f-42d5-bb5d-dfe8847fb9e6)"

This only occurs for this particular NHS Number. Please note this is the same NHS Number which Issue 191 was raised for. Could you please confirm this is a data issue rather than a defect please?

**TEST STEPS TO REPRODUCE ISSUE**

1. _Open Simulated Login Page:_ Open internet browser and enter url: https:\\localhost:44375
2. _Sign In to access user restricted SCR API and display SCR UI:_ Click 'Sign In'
3. _Find NHS Number:_ Click 'GP System'. In 'NHS Number' field enter NHS Number from 'SCR-Meddbase Test Data'; _9693041488_ . Click 'Find'
4. _Update consent to 'Emergency access to view SCR':_ Click radio button for 'Emergency access to view SCR' and then 'Update'. 

**EXPECTED RESULT**

Consent to be updated for patient successfully.  HTTP Status code of 201 with description 'Permission successfully updated' received for 'Update patient's consent to share SCR' (Send audit event) response.

**ADDITIONAL INFO**

Please see Send Audit Event request and response files attached. I have also attached files for a successful 'Update patient's consent to share SCR' response with another NHS Number (_9693041364_).

<img width="958" alt="GP System_9693041488_Emergency Consent Error" src="https://user-images.githubusercontent.com/81386191/112536539-86770780-8da5-11eb-962e-3e0af5e81502.png">

[GP System_9693041488_Send Audit_Event Request-text.txt](https://github.com/NHSDigital/summary-care-record-api/files/6207555/GP.System_9693041488_Send.Audit_Event.Request-text.txt)
[GP System_9693041488_Send Audit_Event Response-text.txt](https://github.com/NHSDigital/summary-care-record-api/files/6207556/GP.System_9693041488_Send.Audit_Event.Response-text.txt)

[GP System_9693041364_Send Audit_Event Request_Success-text.txt](https://github.com/NHSDigital/summary-care-record-api/files/6207639/GP.System_9693041364_Send.Audit_Event.Request_Success-text.txt)
[GP System_9693041364_Send Audit_Event Response_Success-text.txt](https://github.com/NHSDigital/summary-care-record-api/files/6207640/GP.System_9693041364_Send.Audit_Event.Response_Success-text.txt)

**Comment by dawidskainos** [comment]
This one is failing due to Spine error - 404 NOT_FOUND. Will investigate with NHS.

**Comment by michael-kainos** [comment]
@jhoey-med This is a data issue. As discussed with @Kusnaditjung This patient does not have a SCR existing already in spine. A GP Summary upload would have to be performed first.
