### ISSUE TITLE
Incorrect rendering of the Uploaded GP Summary in SCR

### ISSUE THREAD

**Issue by AndrewGuiseley** [NHSDigital/summary-care-record-api#220]
There appears to be rendering issues when uploading the GP Summary in to SCRa.

When viewing the SCR (via the national app), the rendering is incorrect please see the attachment for further details.

![Rendering SCR](https://user-images.githubusercontent.com/28979906/113395443-c46dc000-9391-11eb-8410-ed53129dc8c9.png)

Also attached is the Prsentation Text spec which may help defining which tags the SCR info should be included in.
[GP Summary Presentation Text Specification v2.0.xlsx](https://github.com/NHSDigital/summary-care-record-api/files/6248426/GP.Summary.Presentation.Text.Specification.v2.0.xlsx)

**Comment by dawidskainos** [comment]
Fix deployed to INT and ready for re-test. Please note that you'll need to upload new SCR and then retrieve it to test it. Previously uploaded records will remain broken.

**Comment by AndrewGuiseley** [comment]
Re-tested after the fix was deployed on a round trip SCR i.e. SCR wit Covod codes was retrieved and then the contents re-loaded using a new NHS number - rendering looks correct. Closed.
